### ISSUE TITLE
RSS seems to be broken

### ISSUE THREAD

**Issue by greasan** [thesassway/thesassway.com#51]
Hello,

I have problems to fetch your RSS at Feedburner.

Chrome (build 35.0.1916.153) shows a white page and Selfoss don't like line 147:

> error loading feed content for The Sass Way: This XML document is invalid, likely due to invalid characters. XML error: Mismatched tag at line 147, column 15

Greetings.

**Comment by mgiulio** [comment]
Me too.

Cannot subscribe with Blogtrottr.

Visiting http://feeds.feedburner.com/thesassway with Chrome I get the following error message:

```
This page contains the following errors:

error on line 664 at column 15: Opening and ending tag mismatch: content line 0 and script
Below is a rendering of the page up to the first error.

...

```

Firefox Live Bookmarks seem fine.

**Comment by Songworks** [comment]
Doesn't work in Thunderbird either. Validation:
https://validator.w3.org/feed/check.cgi?url=http://feeds.feedburner.com/thesassway

I believe it might be because of the article "Inverse trigonometric functions with Sass" [1]
There's a script tag that starts with: "% <![CDATA[" and ends with: "%]]>".
Not sure what the % is for there, but it might throw the cdata off?
Additionally the cdata should be unnecessary there anyway, so removing it might fix it?

[1] http://thesassway.com/advanced/inverse-trigonometric-functions-with-sass

**Comment by Songworks** [comment]
The CDATA mentioned in my earlier comment IS responsible for the error. It ends the CDATA section that is added (by whatever creates the xml feed I suppose?) around the whole article prematurely.

Not sure why I didn't saw it before...

**Comment by bertheyman** [comment]
Just to give this some attention again - still broken unfortunately.

**Comment by jlong** [comment]
I've updated the feed to just use summaries to avoid this. Does it work for you now?

So sorry for the long delay in fixing this!

**Comment by bertheyman** [comment]
It's working now - thanks a lot for fixing!
